### ISSUE TITLE
[Design] 메인 페이지 레이아웃 작성

### ISSUE THREAD

**Issue by akuby21** [kakao-tech-campus-2nd-step3/Team22_Android#1]
## 어떤 페이지인가요?
메인 페이지에 해당하는 레이아웃(xml)을 구현합니다.
![image](https://github.com/user-attachments/assets/5ee0cc72-6838-460e-8535-ea95a1328e59)

## To-Do
- [x] 기본 페이지 레이아웃 구현
- [x] 상단 탭으로 정렬기준 변경
- [ ] 반응 보내기 레이아웃 구현
