### ISSUE TITLE
[Design] 공유페이지 레이아웃 마무리

### ISSUE THREAD

**Issue by anyooin** [kakao-tech-campus-2nd-step3/Team22_Android#15]
## 어떤 페이지인가요?
> 공유 페이지에 해당하는 레이아웃(xml)을 마무리합니다.

## To-Do
- [x] 정렬 방법 선택하는 스피너만들기
- [x] 전체 선택 버튼 커스텀하기
- [x] 카테고리 선택 selector + radioButton
- [x] 친구 선택시 배경(회색 불투명 배경) 추가하기
