### ISSUE TITLE
[Design] 친구 페이지 레이아웃 수정 및 추가

### ISSUE THREAD

**Issue by nJiyeon** [kakao-tech-campus-2nd-step3/Team22_Android#17]
## 어떤 페이지인가요?
> 
<img width="200" img height="500" alt="image" src="https://github.com/user-attachments/assets/4122ddcd-ffa8-4fc7-a354-3bb3d65ae106">
<img width="200" img height = "500" alt="image" src="https://github.com/user-attachments/assets/5ff7b6b6-3df3-46c2-8064-847c0bb20e9e">
<img width="200" img height = "500" alt="image" src="https://github.com/user-attachments/assets/2ccb0f90-cd5f-4732-8223-f5928ba203fa">

## To-Do
- [x] 친구 페이지 Recyclerview 구현하기
- [x] 대기 중인 친구 항목 구현하기
- [x] #21
- [x] 친구 항목 내의 버튼 추가하기
- [x] 새로운 친구 항목 내의 버튼 추가하기
- [x] 회원 프로필 조회 화면 수정하기

## 참고 자료
> 나중에 추가하겠습니다 ~
