### ISSUE TITLE
[Design] 회원가입/로그인 페이지, 위젯 레이아웃 작성

### ISSUE THREAD

**Issue by akuby21** [kakao-tech-campus-2nd-step3/Team22_Android#2]
## 어떤 페이지인가요?
회원가입, 로그인 페이지 및 바탕화면의 위젯의 레이아웃을 구성합니다.
![image](https://github.com/user-attachments/assets/baabbd3e-e10e-4c81-82b1-d1d9a008a633) ![image](https://github.com/user-attachments/assets/6298acac-9dc8-43f5-b93f-031ea4141ef1)  ![image](https://github.com/user-attachments/assets/b456d193-9b20-40f8-bdd9-7afb16e37d1b)

## To-Do
- [x] 로그인 페이지 레이아웃 작성
- [x] 회원가입 페이지 레이아웃 작성
- [x] 마이페이지 레이아웃 작성
- [ ] 위젯 레이아웃 작성
