### ISSUE TITLE
[Design] 친구 페이지 레이아웃 작성

### ISSUE THREAD

**Issue by akuby21** [kakao-tech-campus-2nd-step3/Team22_Android#3]
## 어떤 페이지인가요?
친구 페이지에 해당하는 레이아웃(xml)을 구현합니다.
![image](https://github.com/user-attachments/assets/540e4950-e173-4f8e-8895-c93c0942f2b7) ![image](https://github.com/user-attachments/assets/8cfbd654-3c13-43fc-a435-faf451f0abfa) ![image](https://github.com/user-attachments/assets/d9931dc3-f0de-4877-8cdf-b23345ac25e0)

## To-Do
- [ ] 친구 목록 페이지 레이아웃 작성
- [x] 친구 검색 페이지 레이아웃 작성
- [x] 친구 조회 페이지 레이아웃 작성
