### ISSUE TITLE
[Feature] 바텀시트에서 선택한 정보 넘기기

### ISSUE THREAD

**Issue by anyooin** [kakao-tech-campus-2nd-step3/Team22_Android#31]
## 어떤 기능인가요?
> 바텀시트에서 선택한 친구정보과, 입력한 코멘트를 저장하고 다른 액티비티로 넘기기

## To-Do
- [x] 바텀시트에 2가지 타입의 item 띄우기
- [x] 바텀시트에서 선택한 사람의 배경이 바뀌도록(회색효과)
- [x] 선택한 사람과 코멘트 저장
- [x] 저장한 정보들 넘겨서 보여주기
- [x] 친구전체선택 버튼
- [x] Activity를 fragment로 바꾸기
