### ISSUE TITLE
[Feature] 친구 관리 기능 구현

### ISSUE THREAD

**Issue by nJiyeon** [kakao-tech-campus-2nd-step3/Team22_Android#33]
## 어떤 기능인가요?
> 친구 관리 기능을 구현합니다.
> 각 친구 목록의 버튼에 맞게 동작하는 기능입니다.
> 기존의 코드에서 가지고 있던 오류를 수정합니다.

## To-Do
- [x] 수락, 거절, 삭제 버튼을 눌렀을 때 각 버튼에 맞게 친구 목록에 반영하기
- [x] 친구 recyclerview를 누르면 친구 상세 페이지로 넘어가도록 구현하기
- [x] 액티비티에 있던 mockdata Repository 파일로 옮기기
- [x] mock data에서 아이디 못 받아오는 오류 수정하기
- [x] 데이터 로직을 viewmodel로 옮겨서 유지보수 용이하도록 수정하기
<br>
## 관련 이슈
#17 : 대기 중인 친구 목록을 수정하면서 내 친구 목록과 겹쳐 보이는 문제가 발생하여 5주차에 함께 해결하고자 합니다!

## 참고 자료
[Hilt를 활용한 의존성 주입](https://developer.android.com/training/dependency-injection/hilt-android?hl=ko)
[데이터 바인딩과 MVVM](https://june0122.github.io/2021/06/01/android-bnr-19/)
