### ISSUE TITLE
[Design] 공유 페이지 레이아웃 작성

### ISSUE THREAD

**Issue by akuby21** [kakao-tech-campus-2nd-step3/Team22_Android#4]
## 어떤 페이지인가요?
공유 페이지에 해당하는 레이아웃(xml)을 구현합니다.
![image](https://github.com/user-attachments/assets/18e51106-91c6-4aa8-922a-748cfa448ea8) ![image](https://github.com/user-attachments/assets/a8006012-c5cf-431f-a91e-1254a279887c)

## To-Do
- [x] 노래 목록 페이지 레이아웃 작성
- [x] 공유 페이지 레이아웃 작성
- [x] 공유 바텀 시트 레이아웃 작성
