### ISSUE TITLE
[Feature] 친구 상세 페이지 화면 연결 수정

### ISSUE THREAD

**Issue by nJiyeon** [kakao-tech-campus-2nd-step3/Team22_Android#46]
## 어떤 기능인가요?
> 친구 상태에 따라 상세 페이지를 달리 합니다.

## To-Do
- [x] 친구 상태에 따라 상세 페이지를 다르게 하기
- [x] Hilt를 이용한 의존성 주입하기
- [x] Livedata를 stateflow로 바꾸기
- [x] Retrofit 적용하기

## 관련 이슈
> #33 

## 참고 자료
> 따로 학습하며 추가하도록 하겠습니다!
